In [14]:
# Data cleaning

import pandas as pd

df = pd.read_csv("student_success.csv")

# print(df.shape)

# df.info()

display(df)
display(df["Hours_attended"].sum())
display(df.isnull()["Gender"].sum())
display(df.isnull().sum())
# df.duplicated()

df["Success_exam"] = df["Success_exam"].str.replace("Yes", "Y")
df["Success_exam"] = df["Success_exam"].str.replace("No", "N")

df["Success_exam"] = df["Success_exam"].fillna("N")

df

avg_hours_attended = df["Hours_attended"].mean()

df["Hours_attended"] = df["Hours_attended"].fillna(avg_hours_attended)

    Gender   Courses  Hours_attended  Hours_prepared Success_exam
0     Male   Science            20.0             7.0            Y
1     Male  Commerce             4.0             4.0           No
2   Female   Science          2800.0            14.0          Yes
3     Male      Arts            18.0             8.0          Yes
4     Male  Commerce            12.0             NaN            N
5   Female   Science            24.0            12.0          NaN
6   Female      Arts            26.0            11.0          Yes
7     Male  Commerce             8.0             3.0            N
8   Female   Science            25.0            14.0          Yes
9   Female      Arts            10.0             4.0            N
10    Male  Commerce             NaN            12.0          Yes
11  Female      Arts            12.0             8.0           No
12    Male      Arts            10.0             7.0            N
13  Female   Science            29.0             NaN            Y
14    Male   Science            30.0            14.0          Yes
15  Female  Commerce            22.0            11.0          Yes
16    Male   Science            27.0            15.0          NaN
17  Female      Arts            20.0            10.0            Y
18    Male  Commerce             9.0            12.0           No
19  Female   Science            25.0            14.0          Yes
20    Male      Arts            18.0             8.0          Yes
21  Female  Commerce           180.0            40.0          NaN

np.float64(3329.0)

np.int64(0)

Gender            0
Courses           0
Hours_attended    1
Hours_prepared    2
Success_exam      3
dtype: int64

In [18]:
df.duplicated()

df = df.drop_duplicates()

df.describe()

df.values

df.Courses.values

<StringArray>
[ 'Science', 'Commerce',  'Science',     'Arts', 'Commerce',  'Science',
     'Arts', 'Commerce',  'Science',     'Arts', 'Commerce',     'Arts',
     'Arts',  'Science',  'Science', 'Commerce',  'Science',     'Arts',
 'Commerce', 'Commerce']
Length: 20, dtype: str

In [10]:
# Identifying Categorical and Numerical Columns

df['Gender'].dtype == 'str'

df['Hours_attended'].dtype == 'float'

True

In [13]:
# Identifying Unique Data in Categorical Columns

df[['Gender', 'Courses']].nunique()

Gender     2
Courses    3
dtype: int64

In [ ]:
# Encoding:

# One-hot encoding

dt = {
    'Customer': ['A', 'B', 'C', 'D'],
    'Payment_Method': ['Cash', 'Card', 'Transfer', 'Card']
}

df = pd.DataFrame(data=dt)

display(df)

# One hot encoding with pandas
encoded_df = pd.get_dummies(df, columns=['Payment_Method'], dtype=int)

  Customer Payment_Method
0        A           Cash
1        B           Card
2        C       Transfer
3        D           Card

  Customer  Payment_Method_Card  Payment_Method_Cash  Payment_Method_Transfer
0        A                    0                    1                        0
1        B                    1                    0                        0
2        C                    0                    0                        1
3        D                    1                    0                        0

In [ ]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

encoded_col = label_encoder.fit_transform(df['Payment_Method'])

encoded_col

array([1, 0, 2, 0])

In [ ]:
# Splitting the Data in x and y as Training and Test

from sklearn.model_selection import train_test_split

train_test_split()